filebeat.inputs:
  - type: filestream
    paths:
      - /var/log/auth.log
      - /var/log/nginx/access.log
      - /var/log/nginx/error.log
    tags: ["serverlogs"]

# =============================================

output.kafka:
  enabled: true
  hosts: ["192..168.37.132:9092"]
  topic: "server-logs"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
    #  compression: gzip
  codec.json:
    pretty: false